language: python
sudo: false
python:
  - "3.5"
branches:
  only:
    - master
addons:
 apt:
   packages:
   - pandoc
   - xsltproc
install:
  - pip install xml2rfc mako
script:
  - make
after_success:
  - mkdir gh-pages
  - cd gh-pages
  - mv ../*.txt ../*.html .
  - ../.travis.d/make-index.py . > index.html
  - cd ..
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # set this in travis-ci dashboard
  on:
    branch: master
  local_dir: gh-pages
